server:
  port: 8081
spring:
  application:
    # 该值为存入日志ES中的index,需要填写
    name: logger-simple

cloud:
  # kafka配置文件的路径
  logger-kafka: local:kafka/logger-producer.properties
  KF_LOG_PRO: local:kafka/logger-producer.properties
