server:
  port: 8082
spring:
  application:
    # 该值为存入日志ES中的index,需要填写
    name: logger-simple
  common:
    # 保存到哪,支持配置kafka和file两种值,注意,该值必须填写
    log-save-to: kafka
    # 该配置可以不写,默认为error
    log-level: info
helium:
  service:
    log:
      consumer: true
      annotation: true

cloud:
  # kafka配置文件的路径
  KF_LOG_CON: local:kafka/logger-consumer.properties
